In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Research_Frameworks")
from BQCN.DT.FACT.VPTA.STAM1.STAM1 import *

In [2]:
ed = dai.query(f"SELECT DISTINCT date FROM cn_stock_bar1d WHERE date >= '2024-01-01' ORDER BY date DESC").df()['date'].iloc[0].strftime("%Y-%m-%d")
sd = '2024-10-18'

instruments = ['600519.SH']

In [3]:
data_generator = CNDT_FACT_VPTA_STAM1(sd, ed, instruments)

In [4]:
data_generator.alpha_vpta_mavg("close", 5)

                    date instrument  alpha_vpta_mavg_close_5
0    2024-10-18 09:25:00  600519.SH                 1494.222
1    2024-10-18 09:31:00  600519.SH                 1495.006
2    2024-10-18 09:32:00  600519.SH                 1494.680
3    2024-10-18 09:33:00  600519.SH                 1494.520
4    2024-10-18 09:34:00  600519.SH                 1495.194
...                  ...        ...                      ...
5779 2024-11-20 14:56:00  600519.SH                 1544.438
5780 2024-11-20 14:57:00  600519.SH                 1544.520
5781 2024-11-20 14:58:00  600519.SH                 1544.720
5782 2024-11-20 14:59:00  600519.SH                 1544.688
5783 2024-11-20 15:00:00  600519.SH                 1544.652

[5784 rows x 3 columns]

In [5]:
data_generator.alpha_vpta_MACD()

,date,instrument,alpha_vpta_MACD_DIF_26_13_9,alpha_vpta_MACD_DEA_26_13_9,alpha_vpta_MACD_HIST_26_13_9
0,2024-10-18 09:25:00,600519.SH,-2.098676,-1.905780,-0.192896
1,2024-10-18 09:31:00,600519.SH,-1.747038,-1.874032,0.126994
2,2024-10-18 09:32:00,600519.SH,-1.831907,-1.865607,0.033700
3,2024-10-18 09:33:00,600519.SH,-1.822787,-1.857043,0.034256
4,2024-10-18 09:34:00,600519.SH,-1.502558,-1.786146,0.283588
...,...,...,...,...,...
5779,2024-11-20 14:56:00,600519.SH,0.207909,0.277174,-0.069266
5780,2024-11-20 14:57:00,600519.SH,0.208127,0.263365,-0.055238
5781,2024-11-20 14:58:00,600519.SH,0.206098,0.251912,-0.045814
5782,2024-11-20 14:59:00,600519.SH,0.202306,0.241991,-0.039684
5783,2024-11-20 15:00:00,600519.SH,0.197157,0.233024,-0.035867