In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Research_Frameworks")
from BQCN.DT.FACT.VPTA.FTAD1.FTAD1 import *

In [2]:
ed = dai.query(f"SELECT DISTINCT date FROM cn_stock_bar1d WHERE date >= '2024-01-01' ORDER BY date DESC").df()['date'].iloc[0].strftime("%Y-%m-%d")
sd = '2024-10-01'

In [3]:
data_generator = CNDT_FACT_VPTA_FTAD1(sd, ed)

In [4]:
data_generator.alpha_vpta_mavg("close", 5)

            date  instrument  alpha_vpta_mavg_close_5
0     2024-10-08  AP0000.CZC                6938.7278
1     2024-10-08   AP410.CZC                7116.6000
2     2024-10-08   AP411.CZC                6745.8000
3     2024-10-08   AP412.CZC                6884.6000
4     2024-10-08   AP501.CZC                6936.0000
...          ...         ...                      ...
27990 2024-11-18  zn2508.SHF               23880.0000
27991 2024-11-18  zn2509.SHF               23812.0000
27992 2024-11-18  zn2510.SHF               23772.0000
27993 2024-11-18  zn2511.SHF                      NaN
27994 2024-11-18  zn8888.SHF               24651.0000

[27995 rows x 3 columns]

In [6]:
data_generator.alpha_vpta_MACD()

,date,instrument,alpha_vpta_MACD_DIF_26_13_9,alpha_vpta_MACD_DEA_26_13_9,alpha_vpta_MACD_HIST_26_13_9
0,2024-10-08,AP0000.CZC,21.399568,17.361338,4.038229
1,2024-10-08,AP410.CZC,65.272308,22.725514,42.546794
2,2024-10-08,AP411.CZC,24.069621,22.081747,1.987874
3,2024-10-08,AP412.CZC,34.754506,28.453075,6.301431
4,2024-10-08,AP501.CZC,30.902169,28.590775,2.311394
...,...,...,...,...,...
27990,2024-11-18,zn2508.SHF,-21.915562,89.712071,-111.627634
27991,2024-11-18,zn2509.SHF,-57.464643,45.759755,-103.224399
27992,2024-11-18,zn2510.SHF,NaN,NaN,NaN
27993,2024-11-18,zn2511.SHF,NaN,NaN,NaN
27994,2024-11-18,zn8888.SHF,11.786032,97.054670,-85.268638

In [5]:
data_generator.alpha_vpta_PVT()

            date  instrument  alpha_vpta_PVT
0     2024-10-08  AP0000.CZC   742186.324445
1     2024-10-08   AP410.CZC   -22843.612842
2     2024-10-08   AP411.CZC     -676.404424
3     2024-10-08   AP412.CZC     -120.933893
4     2024-10-08   AP501.CZC    -2010.660835
...          ...         ...             ...
27990 2024-11-18  zn2508.SHF        1.410237
27991 2024-11-18  zn2509.SHF       -0.481157
27992 2024-11-18  zn2510.SHF       -1.603976
27993 2024-11-18  zn2511.SHF             NaN
27994 2024-11-18  zn8888.SHF   312172.899143

[27995 rows x 3 columns]