In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Research_Frameworks")
from BQCN.DT.FACT.VPTA.CYFD1.CYFD1 import *

In [2]:
ed = dai.query(f"SELECT DISTINCT date FROM cn_stock_bar1d WHERE date >= '2024-01-01' ORDER BY date DESC").df()['date'].iloc[0].strftime("%Y-%m-%d")
sd = '2024-10-01'

In [3]:
data_generator = CNDT_FACT_VPTA_CYFD1(sd, ed)

In [4]:
data_generator.alpha_vpta_mavg("close", 5)

           date     instrument  alpha_vpta_mavg_close_5
0    2024-10-05   AAVEUSD_PERP                160.11600
1    2024-10-05  ADAUSD_241227                  0.39258
2    2024-10-05  ADAUSD_250328                  0.40034
3    2024-10-05    ADAUSD_PERP                  0.38470
4    2024-10-05   ALGOUSD_PERP                  0.13720
...         ...            ...                      ...
2779 2024-11-21    WLDUSD_PERP                  2.25746
2780 2024-11-21    XLMUSD_PERP                  0.23426
2781 2024-11-21  XRPUSD_241227                  1.14084
2782 2024-11-21  XRPUSD_250328                  1.16708
2783 2024-11-21    XRPUSD_PERP                  1.12578

[2784 rows x 3 columns]

In [5]:
data_generator.alpha_vpta_MACD()

,date,instrument,alpha_vpta_MACD_DIF_26_13_9,alpha_vpta_MACD_DEA_26_13_9,alpha_vpta_MACD_HIST_26_13_9
0,2024-10-05,AAVEUSD_PERP,6.610113,8.044770,-1.434657
1,2024-10-05,ADAUSD_241227,0.007773,0.007101,0.000672
2,2024-10-05,ADAUSD_250328,NaN,NaN,NaN
3,2024-10-05,ADAUSD_PERP,0.008170,0.007596,0.000574
4,2024-10-05,ALGOUSD_PERP,0.002169,0.002554,-0.000385
...,...,...,...,...,...
2779,2024-11-21,WLDUSD_PERP,0.056804,0.052618,0.004186
2780,2024-11-21,XLMUSD_PERP,0.034571,0.021536,0.013036
2781,2024-11-21,XRPUSD_241227,0.148724,0.097694,0.051031
2782,2024-11-21,XRPUSD_250328,0.151387,0.099443,0.051945
2783,2024-11-21,XRPUSD_PERP,0.147031,0.096915,0.050116

In [6]:
data_generator.alpha_vpta_PVT()

           date     instrument  alpha_vpta_PVT
0    2024-10-05   AAVEUSD_PERP    1.122758e+06
1    2024-10-05  ADAUSD_241227   -1.425539e+04
2    2024-10-05  ADAUSD_250328   -1.484253e+03
3    2024-10-05    ADAUSD_PERP    3.517360e+07
4    2024-10-05   ALGOUSD_PERP   -1.537175e+06
...         ...            ...             ...
2779 2024-11-21    WLDUSD_PERP    2.304484e+05
2780 2024-11-21    XLMUSD_PERP   -3.846088e+05
2781 2024-11-21  XRPUSD_241227    2.440170e+05
2782 2024-11-21  XRPUSD_250328    1.617218e+05
2783 2024-11-21    XRPUSD_PERP    1.071344e+08

[2784 rows x 3 columns]