In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Research_Frameworks")
from BQCN.DT.FACT.VPTA.CYSD1.CYSD1 import *

In [2]:
ed = dai.query(f"SELECT DISTINCT date FROM cn_stock_bar1d WHERE date >= '2024-01-01' ORDER BY date DESC").df()['date'].iloc[0].strftime("%Y-%m-%d")
sd = '2024-10-01'

In [3]:
data_generator = CNDT_FACT_VPTA_CYSD1(sd, ed)

In [4]:
data_generator.alpha_vpta_mavg("close", 5)

            date     instrument  alpha_vpta_mavg_close_5
0     2024-10-05  1000SATSFDUSD                 0.000321
1     2024-10-05    1000SATSTRY                 0.010973
2     2024-10-05   1000SATSUSDC                 0.000320
3     2024-10-05   1000SATSUSDT                 0.000320
4     2024-10-05       1INCHBTC                 0.000004
...          ...            ...                      ...
55306 2024-11-17         ZROTRY               123.740000
55307 2024-11-17        ZROUSDC                 3.581600
55308 2024-11-17        ZROUSDT                 3.580600
55309 2024-11-17         ZRXBTC                 0.000004
55310 2024-11-17        ZRXUSDT                 0.366660

[55311 rows x 3 columns]

In [5]:
data_generator.alpha_vpta_MACD()

,date,instrument,alpha_vpta_MACD_DIF_26_13_9,alpha_vpta_MACD_DEA_26_13_9,alpha_vpta_MACD_HIST_26_13_9
0,2024-10-05,1000SATSFDUSD,1.255708e-06,2.168261e-06,-9.125526e-07
1,2024-10-05,1000SATSTRY,5.484842e-05,8.482117e-05,-2.997275e-05
2,2024-10-05,1000SATSUSDC,1.184903e-06,2.150283e-06,-9.653794e-07
3,2024-10-05,1000SATSUSDT,1.134956e-06,2.098336e-06,-9.633801e-07
4,2024-10-05,1INCHBTC,9.858863e-09,1.602379e-08,-6.164926e-09
...,...,...,...,...,...
55306,2024-11-17,ZROTRY,-5.088181e-01,-1.425517e+00,9.166988e-01
55307,2024-11-17,ZROUSDC,-1.930243e-02,-4.545848e-02,2.615605e-02
55308,2024-11-17,ZROUSDT,-1.980285e-02,-4.603732e-02,2.623447e-02
55309,2024-11-17,ZRXBTC,-1.662850e-07,-1.672105e-07,9.255608e-10
55310,2024-11-17,ZRXUSDT,1.207196e-02,7.591139e-03,4.480823e-03

In [6]:
data_generator.alpha_vpta_PVT()

            date     instrument  alpha_vpta_PVT
0     2024-10-05  1000SATSFDUSD    9.535328e+09
1     2024-10-05    1000SATSTRY    2.858320e+11
2     2024-10-05   1000SATSUSDC    1.724455e+09
3     2024-10-05   1000SATSUSDT    1.251411e+12
4     2024-10-05       1INCHBTC    1.699176e+07
...          ...            ...             ...
55306 2024-11-17         ZROTRY    3.343542e+06
55307 2024-11-17        ZROUSDC    2.201503e+05
55308 2024-11-17        ZROUSDT    2.157320e+07
55309 2024-11-17         ZRXBTC    2.671383e+08
55310 2024-11-17        ZRXUSDT    6.324127e+08

[55311 rows x 3 columns]