In [1]:
import dai
import pandas as pd

In [2]:
sql = """

WITH 
data_base AS (
    SELECT date
    FROM all_trading_days
    WHERE market_code = 'CN'
    QUALIFY date >= '1991-01-01'
)

SELECT 

    date,
    ROW_NUMBER(date) AS date_index,

    CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0')) AS dt_year,
    CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0'), LPAD(CAST(quarter(date) AS CHAR), 2, '0')) AS dt_quarter,
    CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0'), LPAD(CAST(month(date) AS CHAR), 2, '0')) AS dt_month,
    CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0'), LPAD(CAST(week(date) AS CHAR), 2, '0'))  AS dt_week,
    CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0'), LPAD(CAST(month(date) AS CHAR), 2, '0'), LPAD(CAST(day(date) AS CHAR), 2, '0')) AS dt_day,
    -- CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0'), LPAD(CAST(month(date) AS CHAR), 2, '0'), LPAD(CAST(day(date) AS CHAR), 2, '0'), LPAD(CAST(hour(date) AS CHAR), 2, '0')) AS dt_hour,
    -- CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0'), LPAD(CAST(month(date) AS CHAR), 2, '0'), LPAD(CAST(day(date) AS CHAR), 2, '0'), LPAD(CAST(hour(date) AS CHAR), 2, '0'), LPAD(CAST(minute(date) AS CHAR), 2, '0')) AS dt_minute,
    -- CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0'), LPAD(CAST(month(date) AS CHAR), 2, '0'), LPAD(CAST(day(date) AS CHAR), 2, '0'), LPAD(CAST(hour(date) AS CHAR), 2, '0'), LPAD(CAST(minute(date) AS CHAR), 2, '0'), LPAD(CAST(second(date) AS CHAR), 2, '0')) AS dt_second,
    -- CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0'), LPAD(CAST(month(date) AS CHAR), 2, '0'), LPAD(CAST(day(date) AS CHAR), 2, '0'), LPAD(CAST(hour(date) AS CHAR), 2, '0'), LPAD(CAST(minute(date) AS CHAR), 2, '0'), LPAD(CAST(second(date) AS CHAR), 2, '0'), LPAD(CAST(millisecond(date) AS CHAR), 3, '0')) AS dt_millisecond,
    -- CONCAT(LPAD(CAST(year(date) AS CHAR), 4, '0'), LPAD(CAST(month(date) AS CHAR), 2, '0'), LPAD(CAST(day(date) AS CHAR), 2, '0'), LPAD(CAST(hour(date) AS CHAR), 2, '0'), LPAD(CAST(minute(date) AS CHAR), 2, '0'), LPAD(CAST(second(date) AS CHAR), 2, '0'), LPAD(CAST(millisecond(date) AS CHAR), 3, '0'), LPAD(CAST(microsecond(date) AS CHAR), 3, '0')) AS dt_microsecond,
    
    IF(dt_year != LAG(dt_year, 1)  OVER (ORDER BY date), 1, 0) AS is_year_start,
    IF(dt_year != LAG(dt_year, -1) OVER (ORDER BY date), 1, 0) AS is_year_end,
    IF(dt_quarter != LAG(dt_quarter, 1)  OVER (ORDER BY date), 1, 0) AS is_quarter_start,
    IF(dt_quarter != LAG(dt_quarter, -1) OVER (ORDER BY date), 1, 0) AS is_quarter_end,
    IF(dt_month != LAG(dt_month, 1)  OVER (ORDER BY date), 1, 0) AS is_month_start,
    IF(dt_month != LAG(dt_month, -1) OVER (ORDER BY date), 1, 0) AS is_month_end,
    IF(dt_week != LAG(dt_week, 1)  OVER (ORDER BY date), 1, 0) AS is_week_start,
    IF(dt_week != LAG(dt_week, -1) OVER (ORDER BY date), 1, 0) AS is_week_end,

    
    ROW_NUMBER() OVER (PARTITION BY dt_year    ORDER BY date) AS day_of_year_trading,
    ROW_NUMBER() OVER (PARTITION BY dt_quarter ORDER BY date) AS day_of_quarter_trading,
    ROW_NUMBER() OVER (PARTITION BY dt_month   ORDER BY date) AS day_of_month_trading,
    ROW_NUMBER() OVER (PARTITION BY dt_week    ORDER BY date) AS day_of_week_trading,
    
    dayofyear(date)  AS day_of_year_nature,
    dayofmonth(date) AS day_of_month_nature,
    dayofweek(date)  AS day_of_week_nature,

FROM data_base

ORDER BY date

"""

df = dai.query(sql).df()
df

,date,date_index,dt_year,dt_quarter,dt_month,dt_week,dt_day,is_year_start,is_year_end,is_quarter_start,...,is_month_end,is_week_start,is_week_end,day_of_year_trading,day_of_quarter_trading,day_of_month_trading,day_of_week_trading,day_of_year_nature,day_of_month_nature,day_of_week_nature
0,1991-01-02,1,1991,199101,199101,199101,19910102,0,0,0,...,0,0,0,1,1,1,1,2,2,3
1,1991-01-03,2,1991,199101,199101,199101,19910103,0,0,0,...,0,0,0,2,2,2,2,3,3,4
2,1991-01-04,3,1991,199101,199101,199101,19910104,0,0,0,...,0,0,1,3,3,3,3,4,4,5
3,1991-01-07,4,1991,199101,199101,199102,19910107,0,0,0,...,0,1,0,4,4,4,1,7,7,1
4,1991-01-08,5,1991,199101,199101,199102,19910108,0,0,0,...,0,0,0,5,5,5,2,8,8,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8298,2024-12-25,8299,2024,202404,202412,202452,20241225,0,0,0,...,0,0,0,238,57,18,3,360,25,3
8299,2024-12-26,8300,2024,202404,202412,202452,20241226,0,0,0,...,0,0,0,239,58,19,4,361,26,4
8300,2024-12-27,8301,2024,202404,202412,202452,20241227,0,0,0,...,0,0,1,240,59,20,5,362,27,5
8301,2024-12-30,8302,2024,202404,202412,202401,20241230,0,0,0,...,0,1,0,241,60,21,5,365,30,1
8302,2024-12-31,8303,2024,202404,202412,202401,20241231,0,0,0,...,0,0,0,242,61,22,6,366,31,2

In [4]:
df['day_of_quarter_nature'] = df['date'].apply(lambda x: (x - x.to_period('Q').start_time).days + 1)
df

,date,date_index,dt_year,dt_quarter,dt_month,dt_week,dt_day,is_year_start,is_year_end,is_quarter_start,...,is_week_start,is_week_end,day_of_year_trading,day_of_quarter_trading,day_of_month_trading,day_of_week_trading,day_of_year_nature,day_of_month_nature,day_of_week_nature,day_of_quarter_nature
0,1991-01-02,1,1991,199101,199101,199101,19910102,0,0,0,...,0,0,1,1,1,1,2,2,3,2
1,1991-01-03,2,1991,199101,199101,199101,19910103,0,0,0,...,0,0,2,2,2,2,3,3,4,3
2,1991-01-04,3,1991,199101,199101,199101,19910104,0,0,0,...,0,1,3,3,3,3,4,4,5,4
3,1991-01-07,4,1991,199101,199101,199102,19910107,0,0,0,...,1,0,4,4,4,1,7,7,1,7
4,1991-01-08,5,1991,199101,199101,199102,19910108,0,0,0,...,0,0,5,5,5,2,8,8,2,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8298,2024-12-25,8299,2024,202404,202412,202452,20241225,0,0,0,...,0,0,238,57,18,3,360,25,3,86
8299,2024-12-26,8300,2024,202404,202412,202452,20241226,0,0,0,...,0,0,239,58,19,4,361,26,4,87
8300,2024-12-27,8301,2024,202404,202412,202452,20241227,0,0,0,...,0,1,240,59,20,5,362,27,5,88
8301,2024-12-30,8302,2024,202404,202412,202401,20241230,0,0,0,...,1,0,241,60,21,5,365,30,1,91
8302,2024-12-31,8303,2024,202404,202412,202401,20241231,0,0,0,...,0,0,242,61,22,6,366,31,2,92

In [6]:
ds = dai.DataSource("mldt_cn_trading_calendar")

def update_df(df_new):
    df_new = df
    return df_new

ds.apply_bdb(update_df, as_type=pd.DataFrame)

dai.DataSource("mldt_cn_trading_calendar")

In [7]:
dai.DataSource.write_bdb(
    data=df,
    id="mldt_cn_trading_calendar",
    unique_together=["date"],
    indexes=["date"],
)

dai.DataSource("mldt_cn_trading_calendar")